#169257392 Set up Docker
andela/boondocks-bn-backend pull request #10
Opened 2019-11-05 20:38 UTC by Mastel22

#### What does this PR do?
Sets up Docker
#### Description of Task to be completed?

- [X] Added Dockerfile
- [X] Added .dockerignore

#### How should this be manually tested?

- Git clone this repo
- run npm install
-  run docker images
-  run docker run
- run docker ps
#### Any background context you want to provide?
-N/A
#### What are the relevant pivotal tracker stories?
[#169257392](https://www.pivotaltracker.com/story/show/169257392)
#### Screenshot
None
#### Questions:
None

2019-11-06 08:06 UTC, timolinn reviewed
Can we put a hold on this feature till next week? We'll come back to this once we have a functional base application.

2019-11-06 08:07 UTC, timolinn commented
Closing it now, will reopen when base app is functional.

2019-11-19 04:25 UTC, b0nbon1 commented on package.json
>      "dotenv": "^6.0.0",
Great work but why did you move babel to the dependencies?

2019-11-19 13:51 UTC, timolinn requested changes
Please add documentation for running and setup. Do this in the `README.md` file.

2019-11-19 21:20 UTC, Mastel22 commented
> Please add documentation for running and setup. Do this in the `README.md` file.



> Please add documentation for running and setup. Do this in the `README.md` file.

Yes, sure

2019-11-21 22:35 UTC, timolinn submitted a review, later dismissed

2019-11-22 07:01 UTC, b0nbon1 submitted a review, later dismissed
Looks good to me

2019-11-25 09:15 UTC, gildniy requested changes
Looks good, but I think by `.docker-compose` in the PR description you meant `docker-compose.yml` in the commit.

2019-11-25 09:47 UTC, Mastel22 commented
> I think by `.docker-compose` in the PR description you meant `docker-compose.yml` in the commit.

Oh yeah.Resolved

2019-11-25 09:47 UTC, gildniy approved these changes
Looks good to be merged!

2019-11-25 09:50 UTC, b0nbon1 approved these changes
Good work.

2019-11-25 13:56 UTC, timolinn approved these changes

2019-11-25 13:56 UTC, merged