#169257412 Builds Avail requests for approval
andela/boondocks-bn-backend pull request #48
Opened 2019-11-29 12:04 UTC by b0nbon1

#### What does this PR do?
It filters the requests and fetches the open requests from users to their line manager for approval.
#### Description of Task to be completed?
- [X] fetch requests for approval to the direct report manager
- [X] check the line manager
- [X] filter the requests with status open
#### How should this be manually tested?
- git clone the repo
- run `npm install` to install dependencies
- run `npm run migrate` to update the tables
- run signup two users with the data on the [Postman workspace](https://boondocks1.postman.co/collections/9182502-c1342d8c-d546-4268-a362-6b65d54804fb?version=latest&workspace=50227f6a-f123-4432-ba31-3b772d690b64)
- update one to be a manager by using [super user endpoint](https://boondocks1.postman.co/collections/9182502-c1342d8c-d546-4268-a362-6b65d54804fb?version=latest&workspace=50227f6a-f123-4432-ba31-3b772d690b64#dd2474b8-3d2a-47ad-a2e4-eada7bb0d69e)
- update the other user to the have line manager of the 1st user using [update profile endpoint](https://boondocks1.postman.co/collections/9182502-c1342d8c-d546-4268-a362-6b65d54804fb?version=latest&workspace=50227f6a-f123-4432-ba31-3b772d690b64#67efd549-4ba5-4b1c-bcbd-10bd76be6f73)
- use the user's token to request for trip, get any endpoints [in this collection](https://boondocks1.postman.co/collections/9182502-d4e20d34-995a-4bd4-b509-91ebebccc733?version=latest&workspace=50227f6a-f123-4432-ba31-3b772d690b64)
- the using the token of the manager use avail [request to manager endpoint](https://boondocks1.postman.co/collections/9182502-c3ac8a00-f8fa-4110-bea9-a7e7e8555d41?version=latest&workspace=50227f6a-f123-4432-ba31-3b772d690b64) to get all request related to him
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
[#169257412](https://www.pivotaltracker.com/n/projects/2407417/stories/169257412)
#### Screenshots 
![image](https://user-images.githubusercontent.com/46062609/69867021-52bdc780-12ae-11ea-970a-c48c66b2fe93.png)

#### Questions:

2019-11-29 15:19 UTC, gildniy requested changes

2019-11-29 15:19 UTC, gildniy commented on src/middlewares/roleAuthorization.js
> +  checkIsManager(req, res, next) {
I think these 2 check methods can be done into one and pass the allowed roles name array in params

2019-11-29 15:21 UTC, gildniy requested changes

2019-11-29 15:21 UTC, gildniy commented on src/controllers/request.controller.js
>      return Responses.handleSuccess(200, 'Succesfully fetched the request', res, requests);
I think `Succesfully` might be `Successfully`!

2019-11-29 15:21 UTC, gildniy commented on src/controllers/request.controller.js
>      return Responses.handleSuccess(200, 'Succesfully fetched the request', res, requests);
I think `Succesfully` might be `Successfully`!

2019-11-29 15:21 UTC, gildniy commented on src/controllers/request.controller.js
> +    return Responses.handleSuccess(200, 'Succesfully fetched the requests', res, requests);
I think `Succesfully` might be `Successfully`!

2019-11-29 15:29 UTC, gildniy approved these changes
Looks great now, I think it can be merged.

2019-12-02 11:06 UTC, Mastel22 approved these changes
Great job.

2019-12-02 11:23 UTC, nshaphan commented
Great work, but you would edit Pull request description to use actual endpoint instead of links to the postman workspace.
I recommend you also to use the team workspace. To have all endpoint at one place

2019-12-02 11:33 UTC, nshaphan approved these changes

2019-12-02 15:24 UTC, merged