ft(notification): Notification for new travel
andela/boondocks-bn-backend pull request #49
Opened 2019-12-02 07:34 UTC by Mastel22

## What does this PR do?
- Create pull request for notification of new travel
#### Description of Task to be completed?
- [X] added notification middleware
- [X] added socket.io for real time notifications
- [X]  added the cancel email notification endpoint
- [X] added the email notification service
#### How should this be manually tested?
- Navigate to the root folder where you want to copy this repo
- Run `git clone <link to this repo>
- Run `npm i` to install the dependencies
-  Run `npm run watch` to  the start the server
- Use postman to create a trip (check create trip PR)
- Check your email for notification
#### Any background context you want to provide?
- If you haven't used socket.io before please read about it before reviewing this PR
#### What are the relevant pivotal tracker stories?
[#169257407](https://www.pivotaltracker.com/story/show/169257407)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/52410156/69938434-ffce5500-14e5-11ea-9aa0-6f8ea862b2f9.png)

#### Questions:

2019-12-05 13:09 UTC, collinewait commented on src/migrations/20191112101055-create-user.js
> +      allowNull: false
It looks like you updated a migration. You can create a new migration.

2019-12-05 13:28 UTC, gildniy requested changes
Kindly check on a few feedback I left on this PR.

2019-12-05 13:28 UTC, gildniy commented on public/templates/emails/emailVerification.pug
> +html
I think this has been duplicated.

2019-12-05 13:28 UTC, gildniy commented on package.json
> +    "nodemailer-mailgun-transport": "^1.4.0",
I think this package was not used in this branch and may be removed from there.

2019-12-09 08:53 UTC, b0nbon1 approved these changes
I really like how you implemented the `in-app notification` that is by emitting the to the notifications to the user using `socket.io`. Great job
I have reviewed it and I think it's ready to be merged.

2019-12-09 08:53 UTC, gildniy submitted a review, later dismissed
Looks nice, and I think it's ready to be merged.

2019-12-09 10:46 UTC, b0nbon1 submitted a review, later dismissed

2019-12-09 10:52 UTC, nshaphan submitted a review, later dismissed
Great work @Mastel22, This is work is worth the effort.

2019-12-09 11:59 UTC, b0nbon1 approved these changes

2019-12-09 12:02 UTC, gildniy approved these changes
Tested and working. It can be merged, I think.

2019-12-09 12:03 UTC, collinewait approved these changes

2019-12-09 12:03 UTC, merged