#170873930 Fix the requests search data for the line manager
andela/boondocks-bn-backend pull request #82
Opened 2020-01-24 10:46 UTC by gildniy

#### What does this PR do?
Fix the requests search data for the line manager
#### Description of Task to be completed?
- [x] Get all requests under manager report whether open or closed upon search
#### How should this be manually tested?
- clone this repo and open the project 
- install all dependencies using `npm install`
- in postman login as a line manager and go to `/requests/search?byLineManager=true?searchString=open`
#### Any background context you want to provide?
This bug fix task was needed to be done to allow the Line manager to search all request types (all, open and declined) and use the search terms (requester names, travel date, return date, city or country).
#### What are the relevant pivotal tracker stories?
[#170873930](https://www.pivotaltracker.com/story/show/170873930)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2020-01-24 19:58 UTC, RaymondMwaura requested changes

2020-01-24 19:58 UTC, RaymondMwaura commented on src/utils/schemas.js
> -  returnDate: Joi.date().when('type', { is: 'return', then: Joi.required() }).allow(null, ''),
Ask @b0nbon1 about the omission of '.allow(null, '')' since I think he needs it for his feature

2020-01-24 19:58 UTC, RaymondMwaura commented on src/services/request.service.js
> -        as: 'author',
I think @Mastel22 will need this for her comments feature. Ask her if you should omit it.

2020-01-27 14:37 UTC, nshaphan submitted a review, later dismissed
LGTM

2020-01-27 15:05 UTC, RaymondMwaura submitted a review, later dismissed

2020-01-28 10:02 UTC, RaymondMwaura approved these changes
LGTM

2020-01-28 10:07 UTC, b0nbon1 approved these changes
LGTM

2020-01-28 10:08 UTC, nshaphan approved these changes

2020-01-28 11:08 UTC, merged