#17134998 Two factor authentication
andela/boondocks-bn-backend pull request #93
Opened 2020-02-21 04:53 UTC by gildniy

#### What does this PR do?
Creates a 2 factor authentication for the user.
#### Description of Task to be completed?
- add the field for the 2fa type the user uses on the users table
- add the field for the 2fa secret on the users table if the user activated 2fa to login
- add the functionality to optionally setup the 2 fa for the logged in user and this by using authenticator application (like google authenticator or Authy) or SMS text message
- verify if the user can use the 2fa before letting him activate this feature to his account
- add the option for the user to know if he has activated 2fa or not
- add a way for the user to disable 2fa for his account
#### How should this be manually tested?
- Clone the repo and run `npm install` to install the dependencies
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#17134998](https://www.pivotaltracker.com/story/show/171374998)
#### Screenshots (if appropriate)
1. Setup 2FA using SMS Text method
![image](https://user-images.githubusercontent.com/3137192/75004753-d5e95680-5474-11ea-9cab-9cd773cbb140.png)

2. SMS message sent to the user with a 6 digit one minute valid token
![image](https://user-images.githubusercontent.com/3137192/75004893-5445f880-5475-11ea-975c-246c069f4f8c.png)

3. Setup 2FA using Authenticator app method
![image](https://user-images.githubusercontent.com/3137192/75005098-f2d25980-5475-11ea-8289-f301307818da.png)
![image](https://user-images.githubusercontent.com/3137192/75005114-067dc000-5476-11ea-80db-14961aaf9146.png)

4. Validate the user if he is the owner of the account using a received 2fa token
![image](https://user-images.githubusercontent.com/3137192/75005232-6a07ed80-5476-11ea-9913-ef5703bcb81d.png)

5. Check if the user activated 2fa and the activated type
![image](https://user-images.githubusercontent.com/3137192/75005297-a3405d80-5476-11ea-8b7b-e954bf6b1c28.png)

6. Disable 2fa from the user account
![image](https://user-images.githubusercontent.com/3137192/75005349-ca972a80-5476-11ea-862e-70b39bdadb32.png)

#### Questions:
N/A

2020-02-26 18:51 UTC, RaymondMwaura requested changes
Great work Gildas. I have left some comments on some files on changes I think you should make. Also, add validation schema for the these two routes:
- {{{url}}/api/v1/2fa/totp/send-token-text
- {{url}}/api/v1/2fa/totp/verify

2020-02-26 18:51 UTC, RaymondMwaura commented on src/migrations/20191205132450-user.js
>  module.exports = {
I think you should rename this migration to something more descriptive like: '20191205132450-add-2FA-to-users.js'

2020-02-26 18:51 UTC, RaymondMwaura commented on src/controllers/2fa.controller.js
> +    await db.user.update({ twoFAType: type.split('_temp')[0] }, { where: { email: res.locals.user.email } });
I think you should move this to you 2fa service.

2020-02-26 18:51 UTC, RaymondMwaura commented on src/controllers/2fa.controller.js
> +  await messenger(phoneNumber, `Your 6 Digit 60 seconds expiration PassCode is: ${token}`);
I think you can create a variable from this string: ``Your 6 Digit 60 seconds expiration PassCode is: ${token}``, then call it on lines 69 & 77.

2020-02-28 08:36 UTC, gildniy commented on src/migrations/20191205132450-user.js
>  module.exports = {
You're right, I have to put them in their own file

2020-02-28 08:43 UTC, gildniy commented on src/controllers/2fa.controller.js
> +    await db.user.update({ twoFAType: type.split('_temp')[0] }, { where: { email: res.locals.user.email } });
Thanks, let me move this.

2020-02-28 11:39 UTC, gildniy commented
> Great work Gildas. I have left some comments on some files on changes I think you should make. Also, add validation schema for the these two routes:
> 
> * {{{url}}/api/v1/2fa/totp/send-token-text
> * {{url}}/api/v1/2fa/totp/verify

Here I implement the `validation` to `{{url}}/api/v1/2fa/totp/verify` only, as the other route `{{{url}}/api/v1/2fa/totp/send-token-text` the user doesn't directly enter the `phoneNumber and secret` in a form, they are provided from the backend token.

2020-02-28 11:51 UTC, RaymondMwaura approved these changes

2020-02-28 13:19 UTC, RaymondMwaura submitted a review, later dismissed
Great job Gildas! All the endpoints work and all the feedback has been implemented.

2020-03-02 07:32 UTC, nshaphan submitted a review, later dismissed
Great work @gildniy Tested, The feature works fine

2020-03-03 08:30 UTC, b0nbon1 submitted a review, later dismissed
Hey @gildniy Great, I think everything is working okay. May be you would remove the files in the `public/temp` the PR will be good to go

2020-03-03 08:31 UTC, b0nbon1 commented
Your build is failing @gildniy

2020-03-03 09:02 UTC, gildniy commented
> Hey @gildniy Great, I think everything is working okay. May be you would remove the files in the `public/temp` the PR will be good to go

Done

2020-03-03 09:03 UTC, gildniy commented
> Your build is failing @gildniy

Can you please share the error you're getting?

2020-03-03 09:07 UTC, b0nbon1 submitted a review, later dismissed

2020-03-03 09:51 UTC, RaymondMwaura submitted a review, later dismissed
Good job.

2020-03-03 09:54 UTC, nshaphan submitted a review, later dismissed

2020-03-03 14:01 UTC, RaymondMwaura approved these changes
LGTM

2020-03-03 14:14 UTC, nshaphan approved these changes

2020-03-03 14:44 UTC, b0nbon1 approved these changes

2020-03-05 09:46 UTC, merged